import { Bricolage_Grotesque, } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
// import { ThemeProvider } from "next-themes";
import Footer from "@/components/Footer";
import { Toaster } from "react-hot-toast";
import NextThemeProvider from "./provider/NextThemeProvider";


const bricolageGrotesque = Bricolage_Grotesque({
  subsets: ["latin"],
});


export const metadata = {
  title: "StudyNook – Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${bricolageGrotesque.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-background text-foreground">

        {/* <NextThemeProvider> */}
          <Navbar />
          {children}
          <Footer />
        {/* </NextThemeProvider>  */}
        <Toaster />
      </body>
    </html>
  );
}




